description: Desenvolva e publique Workers que executam rotinas da empresa no seu produto com nossa Stack cloud native .NET.
name: mind-dotnet-worker-stack
display-name: Stack Worker
picture: stack.png
category: Backend
compatibility:
  - net5.0
  - net6.0
technologies: 
  - .NET
  - C#
  - Worker
  - Splunk
  - Prometheus
  - Jaeger
  - AWS SQS
  - AWS SNS
  - AWS DynamoDB
  - Docker
  - AWS ECS/Fargate 
about: docs/about.md
use-cases:
  - title: Basic Worker
    content: docs/use-case.md
    stackfile: stackfiles/basic-worker.yaml